# Generated by Django 4.2.4 on 2023-09-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Course',
            new_name='course',
        ),
    ]
