# Generated by Django 4.2.4 on 2023-10-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_rename_course_course_course_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date',
            new_name='joining_date',
        ),
    ]
