# Generated by Django 4.2.4 on 2023-10-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0005_rename_birth_date_student_joining_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='joining_date',
            new_name='Joining_date',
        ),
    ]
