# Generated by Django 4.2.4 on 2023-10-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0006_rename_joining_date_student_joining_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Joining_date',
            new_name='J_date',
        ),
    ]
